# Generated by Django 4.2.17 on 2025-02-28 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=128, verbose_name="タイトル")),
                ("address", models.TextField(blank=True, verbose_name="住所")),
                ("description", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新日")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Salesman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salesman_name", models.CharField(max_length=32)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新日")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("route_name", models.CharField(max_length=32)),
                ("route_description", models.TextField(blank=True, verbose_name="注意点")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                ("update_at", models.DateTimeField(auto_now=True, verbose_name="更新日")),
                (
                    "cities",
                    models.ManyToManyField(related_name="routes", to="solutions.city"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
                (
                    "depot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depot",
                        to="solutions.city",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="salesman",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salesman",
                to="solutions.salesman",
            ),
        ),
    ]
