# Generated by Django 4.2.17 on 2025-03-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="salesmen",
            field=models.ManyToManyField(
                related_name="salesmen", to="solutions.salesman"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="cities",
            field=models.ManyToManyField(related_name="cities", to="solutions.city"),
        ),
    ]
