# Generated by Django 4.2.17 on 2025-02-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="タイトル")),
                ("start", models.CharField(max_length=120, verbose_name="住所")),
                ("spot1", models.CharField(max_length=120, verbose_name="住所")),
                ("spot2", models.CharField(max_length=120, verbose_name="住所")),
                ("spot3", models.CharField(max_length=120, verbose_name="住所")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日")),
            ],
        ),
    ]
