# Generated by Django 4.2.17 on 2025-02-13 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("visualapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cource",
            name="created_by",
            field=models.ForeignKey(
                default="0",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="作成者",
            ),
        ),
    ]
