# Generated by Django 4.2.17 on 2025-04-07 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authsample", "0003_route"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="unknown", max_length=100)),
                ("description", models.TextField(blank=True, verbose_name="備考")),
                ("ans", models.JSONField(default=list)),
                ("path", models.JSONField(default=list)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日")),
            ],
        ),
    ]
