# Generated by Django 4.2.17 on 2025-02-13 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="タイトル")),
                ("depot", models.CharField(max_length=120, verbose_name="拠点")),
                ("spot1", models.CharField(max_length=120, verbose_name="訪問1")),
                ("spot2", models.CharField(max_length=120, verbose_name="訪問2")),
                ("spot3", models.CharField(max_length=120, verbose_name="訪問3")),
                ("spot4", models.CharField(max_length=120, verbose_name="訪問4")),
                ("spot5", models.CharField(max_length=120, verbose_name="訪問5")),
                ("spot6", models.CharField(max_length=120, verbose_name="訪問6")),
                ("spot7", models.CharField(max_length=120, verbose_name="訪問7")),
                ("spot8", models.CharField(max_length=120, verbose_name="訪問8")),
                ("spot9", models.CharField(max_length=120, verbose_name="訪問9")),
                ("spot10", models.CharField(max_length=120, verbose_name="訪問10")),
                ("spot11", models.CharField(max_length=120, verbose_name="訪問11")),
                ("spot12", models.CharField(max_length=120, verbose_name="訪問12")),
                ("spot13", models.CharField(max_length=120, verbose_name="訪問13")),
                ("spot14", models.CharField(max_length=120, verbose_name="訪問14")),
                ("spot15", models.CharField(max_length=120, verbose_name="訪問15")),
                ("spot16", models.CharField(max_length=120, verbose_name="訪問16")),
                ("spot17", models.CharField(max_length=120, verbose_name="訪問17")),
                ("spot18", models.CharField(max_length=120, verbose_name="訪問18")),
                ("spot19", models.CharField(max_length=120, verbose_name="訪問19")),
                ("spot20", models.CharField(max_length=120, verbose_name="訪問20")),
                ("description", models.TextField(blank=True, verbose_name="備考")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作成者",
                    ),
                ),
            ],
        ),
    ]
