# Generated by Django 4.2.17 on 2025-03-20 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restpractice", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="city", name="created_by",),
        migrations.RemoveField(model_name="route", name="created_by",),
        migrations.RemoveField(model_name="salesman", name="created_by",),
    ]
