# Generated by Django 4.2.17 on 2025-03-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restpractice", "0004_solution_delete_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="name",
            field=models.CharField(default="unknown", max_length=100),
        ),
    ]
