# Generated by Django 4.2.17 on 2025-03-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restpractice", "0005_solution_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日"),
        ),
    ]
