# Generated by Django 5.1.6 on 2025-02-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='depot',
            field=models.TextField(blank=True, verbose_name='拠点'),
        ),
    ]
