# Generated by Django 5.1.6 on 2025-02-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_route_depot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='depot',
        ),
        migrations.AddField(
            model_name='route',
            name='depot',
            field=models.ManyToManyField(related_name='depot', related_query_name='to_depot', to='cities.city'),
        ),
    ]
